apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: scalable-app
  labels:
    app.kubernetes.io/name: fastapi-app
    app.kubernetes.io/part-of: scalable-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fastapi-app
  ports:
    - name: http
      port: 80
      targetPort: http
